### ISSUE TITLE
[Bug] 总是会将OpenAI-Compatible的第一个apikey(token)用于请求openai官方地址

### ISSUE THREAD

**Issue by RoadToNowhereX** [GalTransl/GalTransl#168]
在配置文件的OpenAI-Compatible项中设置多个apikey(token)时，总是会将第一个apikey(token)用于请求openai官方地址，即使endpoint设置为本地地址http://127.0.0.1:5001

因此在多个apikey(token)中，第一个总会返回：
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-or-v1*************************************************************8d5b. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by xd2333** [comment]
设置多个token的时候是否是按照如下格式设置的：
```
  OpenAI-Compatible: # (ForGal/gpt4/r1模板)OpenAI API兼容接口通用
    tokens:
      - token: sk-wjqPhWi98LueFZn16dxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        endpoint: https://xxxxxxxxxx # 请求地址，使用转发或第三方API时修改
      - token: sk-wjqPhWi98LueFZn16xxxxxxxxxxxxxxxxxxxxxxxxxx
        endpoint: https://miaodxxxxxxxxxxxx # 请求地址，使用转发或第三方API时修改
```

每个token都要设置endpoint，否则默认会到api.openai.com
